name: Build and Test NodeEditor

on:
  push:

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix: 
        qt_version: [5.13.2, 5.15.2, 6.2.0]
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.13.2
      with:
        version: ${{ matrix.qt_version }}
        aqtversion: ==1.2.2 # miurahr/aqtinstall#288

    # QTBUG-95391
    - name: Install Vulkan SDK
      if: matrix.config.os != 'macos-latest'
      uses: humbletim/setup-vulkan-sdk@v1.0.2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

#     - name: Test
#       working-directory: ${{github.workspace}}/build
#       run: ctest -C ${{env.BUILD_TYPE}}
      
